const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const state={view:'map',mapId:'country-of-time',maps:[],mapMeta:null,mapData:null,site:null,layers:new Map(),layerVisible:new Map(),layerVisuals:new Map(),markerBuckets:new Map(),hover:null,selected:null,scale:1,tx:0,ty:0,drag:null,search:'',aniilog:null,catalog:null,checklist:null,checked:new Set(JSON.parse(localStorage.getItem('aniimo-atlas-checks')||'[]'))};
const layerColors={aniimo:'#86e6d5',items:'#8ea9ff',misc:'#d9a7ff',ambers:'#e6c76f',eggs:'#ff9e86',teleports:'#7ec8ff'};
const vi={aniimo:'Aniimo',items:'Vật phẩm',misc:'Khác',ambers:'Lumen Ember',eggs:'Trứng',teleports:'Dịch chuyển'};
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
async function j(url){const r=await fetch(url);if(!r.ok)throw new Error(url+' '+r.status);return r.json()}
async function init(){
  state.site=await j('data/map_site_data.json'); state.maps=state.site.maps;
  renderMapList(); renderMapButtons(); bindGlobal(); await loadMap(state.mapId); await loadDataViews();
}
function renderMapList(){const box=$('#mapList');box.innerHTML=state.maps.map(m=>`<button class="map-item ${m.id===state.mapId?'active':''}" data-map="${m.id}"><span class="map-item-thumb"><img src="${asset(m.fallback_image||m.image)}" alt="" loading="lazy"></span><span class="map-item-copy"><span class="name">${esc(m.label)}</span><span class="count">${fmt(m.counts?.spawns||0)} vị trí · ${esc(m.world_label||'')}</span></span></button>`).join('');$$('.map-item').forEach(b=>b.onclick=()=>loadMap(b.dataset.map))}
function renderMapButtons(){const box=$('#mapSwitch');box.innerHTML=state.maps.map(m=>`<button class="${m.id===state.mapId?'active':''}" data-map="${m.id}">${esc(m.label)}</button>`).join('');$$('#mapSwitch button').forEach(b=>b.onclick=()=>loadMap(b.dataset.map))}
async function loadMap(mapId){
 state.mapId=mapId; state.mapMeta=state.maps.find(m=>m.id===mapId)||state.maps[0];
 state.mapData=await j(`data/maps/${mapId}.json`);state.layers.clear();state.layerVisible.clear();state.layerVisuals.clear();state.itemIndex=new Map((state.mapData.items||[]).map(x=>[String(x.item_id),x]));state.markerBuckets.clear();state.selected=null;state.hover=null;
 for(const s of state.mapData.spawns){
   const id=s.layer_id||'misc';
   state.layers.set(id,(state.layers.get(id)||0)+1);
   if(!state.layerVisible.has(id))state.layerVisible.set(id,false);
   if(!state.layerVisuals.has(id)){
     const src=state.itemIndex.get(String(s.item_id))||{};
     state.layerVisuals.set(id,{icon:src.icon||'',name:s.display_name||src.display_name||vi[id]||id,marker:s.marker_type||''});
   }
 }
 state.mapMeta.label && ($('#mapTitle').textContent=state.mapMeta.label);
 $('#mapMeta').textContent=`${state.mapMeta.world_label||'Aniimo'} · ${fmt(state.mapData.spawns.length)} vị trí · ${fmt(state.mapData.items.length)} mục`; 
 $('#mapImage').src=state.mapMeta.fallback_image||state.mapMeta.image; $('#mapImage').style.width=state.mapMeta.width+'px';$('#mapImage').style.height=state.mapMeta.height+'px';
 const c=$('#markerCanvas');c.width=state.mapMeta.width;c.height=state.mapMeta.height;c.style.width=state.mapMeta.width+'px';c.style.height=state.mapMeta.height+'px';
 $('#mapWorld').style.width=state.mapMeta.width+'px';$('#mapWorld').style.height=state.mapMeta.height+'px';
 renderMapList();renderMapButtons();renderLayers();fitMap();drawMarkers();
 $('#detailEmpty').hidden=false;$('#detailContent').hidden=true;
}
function renderLayers(){
  const box=$('#layerList');
  const search=($('#layerSearch')?.value||'').trim().toLowerCase();
  const rows=[...state.layers.entries()]
    .sort((a,b)=>(vi[a[0]]||title(a[0])).localeCompare((vi[b[0]]||title(b[0])),'vi'))
    .filter(([id,count])=>{
      const v=state.layerVisuals.get(id)||{};
      return !search || [vi[id],title(id),v.name,v.marker,count].join(' ').toLowerCase().includes(search);
    })
    .map(([id,count])=>{
      const v=state.layerVisuals.get(id)||{};
      const on=!!state.layerVisible.get(id);
      const icon=v.icon?asset(v.icon):'';
      const label=vi[id]||title(id);
      return `<button class="layer-card ${on?'is-on':''}" data-layer="${esc(id)}" aria-pressed="${on}">
        <span class="layer-art" style="--layer-color:${layerColors[id]||'#b7c0ca'}">${icon?`<img src="${icon}" alt="" loading="lazy" onerror="this.style.display='none';this.parentElement.classList.add('fallback')">`:`<span class="layer-fallback-icon">${layerGlyph(id)}</span>`}</span>
        <span class="layer-card-main"><span class="layer-card-top"><b>${esc(label)}</b><em>${fmt(count)}</em></span>
        <span class="layer-card-sub">${esc(v.name||'Lớp bản đồ')}</span>
        <span class="layer-card-state">${on?'Đang hiển thị':'Chạm để hiển thị'}</span></span>
        <span class="layer-check">${on?'✓':'+'}</span>
      </button>`;
    }).join('');
  box.innerHTML=rows||`<div class="layer-no-results">Không tìm thấy lớp phù hợp.</div>`;
  $$('#layerList .layer-card').forEach(b=>b.onclick=()=>{const id=b.dataset.layer;state.layerVisible.set(id,!state.layerVisible.get(id));renderLayers();drawMarkers()});
  updateLayerSummary();
}
function updateLayerSummary(){
  const total=state.layers.size;
  const active=[...state.layerVisible.values()].filter(Boolean).length;
  const el=$('#layerSummary'); if(el)el.textContent=`${active} / ${total} lớp đang bật`;
  const empty=$('#mapExploreEmpty'); if(empty)empty.classList.toggle('hidden',active>0);
  const legend=$('#mapLegend'); if(legend)legend.textContent=active?`${fmt(active)} lớp · ${fmt(countVisibleMarkers())} marker`:'0 lớp · 0 marker';
}
function countVisibleMarkers(){return state.mapData?.spawns?.reduce((n,s)=>n+(state.layerVisible.get(s.layer_id||'misc')?1:0),0)||0}
function layerGlyph(id){return ({aniimo:'◉',items:'✦',misc:'◆',ambers:'✧',eggs:'◌',teleports:'⌖'})[id]||'•'}
function updateStatus(){let visible=state.mapData.spawns.filter(s=>state.layerVisible.get(s.layer_id||'misc')).length;$('#markerStatus').textContent=`${fmt(visible)} / ${fmt(state.mapData.spawns.length)} marker đang hiển thị`}
function fitMap(){const s=$('#mapStage');const pad=30;const sx=(s.clientWidth-pad)/state.mapMeta.width,sy=(s.clientHeight-pad)/state.mapMeta.height;state.scale=Math.min(1,Math.max(.05,Math.min(sx,sy)));state.tx=(s.clientWidth-state.mapMeta.width*state.scale)/2;state.ty=(s.clientHeight-state.mapMeta.height*state.scale)/2;applyTransform()}
function applyTransform(){ $('#mapWorld').style.transform=`translate3d(${state.tx}px,${state.ty}px,0) scale(${state.scale})`; }
function drawMarkers(){const c=$('#markerCanvas'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);for(const m of state.mapData.spawns){if(!state.layerVisible.get(m.layer_id||'misc'))continue;const x=m.normalized?.x!=null?m.normalized.x*c.width:(m.ui_position?.x/state.mapMeta.width||0);const y=m.normalized?.y!=null?m.normalized.y*c.height:(m.ui_position?.y/state.mapMeta.height||0);const id=m.layer_id||'misc';const color=layerColors[id]||'#b7c0ca';let r=3.5;if(id==='aniimo')r=3.3; if(state.selected===m)r=7;ctx.beginPath();ctx.fillStyle=color;ctx.globalAlpha=state.selected===m?.98:.82;ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();if(state.selected===m){ctx.globalAlpha=1;ctx.lineWidth=2;ctx.strokeStyle='#fff';ctx.stroke()} }ctx.globalAlpha=1;updateStatus();updateLayerSummary()}
function worldPoint(ev){const rect=$('#mapStage').getBoundingClientRect();return{x:(ev.clientX-rect.left-state.tx)/state.scale,y:(ev.clientY-rect.top-state.ty)/state.scale}}
function nearestMarker(pt,threshold=22){let best=null,bd=threshold;for(const m of state.mapData.spawns){if(!state.layerVisible.get(m.layer_id||'misc'))continue;const x=(m.normalized?.x||0)*state.mapMeta.width,y=(m.normalized?.y||0)*state.mapMeta.height;const d=Math.hypot(x-pt.x,y-pt.y);if(d<bd){best=m;bd=d}}return best}
function showMarker(m){if(!m)return;state.selected=m;drawMarkers();const src=state.itemIndex.get(String(m.item_id))||{};const icon=src.icon||'';$('#detailEmpty').hidden=true;$('#detailContent').hidden=false;$('#detailContent').innerHTML=`<div class="detail-head"><img class="detail-icon" src="${asset(icon)}" onerror="this.style.display='none'"><div><h2>${esc(m.display_name||src.display_name||'Marker')}</h2><div class="detail-sub">${esc(m.marker_type||m.layer_id||'')} · ${esc(m.region_name||state.mapMeta.label||'')}</div></div></div><div class="detail-block"><div class="detail-title">Thông tin</div><div class="facts"><div class="fact"><label>Lớp</label><b>${esc(vi[m.layer_id]||m.layer_id||'—')}</b></div><div class="fact"><label>Tọa độ</label><b>${Math.round(m.x??0)}, ${Math.round(m.y??0)}</b></div><div class="fact"><label>Khu vực</label><b>${esc(m.area_name||m.area_inferred_name||'—')}</b></div><div class="fact"><label>Độ cao</label><b>${m.height_y!=null?Number(m.height_y).toFixed(1):'—'}</b></div></div></div><div class="detail-block"><div class="detail-title">Tag</div><div class="tag-row"><span class="tag">${esc(m.coordinate_key||'')}</span><span class="tag">${esc(m.level_area_name||'')}</span></div></div><div class="detail-block"><button class="small-btn" id="pinCurrent">${isPinned(m)?'Đã ghim':'＋ Ghim vị trí'}</button></div>`;$('#pinCurrent').onclick=()=>togglePin(m)}
const pins=new Map();function pinKey(m){return m.coordinate_key||`${m.map_id}:${m.x}:${m.y}:${m.item_id}`}function isPinned(m){return pins.has(pinKey(m))}function togglePin(m){const k=pinKey(m);if(pins.has(k)){pins.delete(k);toast('Đã bỏ ghim')}else{pins.set(k,{...m,map_id:state.mapId});toast('Đã ghim vị trí')}showMarker(m)}
function bindMap(){const stage=$('#mapStage');stage.onpointerdown=e=>{state.drag={x:e.clientX,y:e.clientY,tx:state.tx,ty:state.ty};stage.classList.add('dragging');stage.setPointerCapture(e.pointerId)};stage.onpointermove=e=>{const p=worldPoint(e);$('#coordReadout').textContent=`X ${Math.round(p.x)} · Y ${Math.round(p.y)}`;if(state.drag){state.tx=state.drag.tx+(e.clientX-state.drag.x);state.ty=state.drag.ty+(e.clientY-state.drag.y);applyTransform()}};stage.onpointerup=e=>{const moved=state.drag && Math.hypot(e.clientX-state.drag.x,e.clientY-state.drag.y)>4;state.drag=null;stage.classList.remove('dragging');if(!moved){const m=nearestMarker(worldPoint(e),20/state.scale);showMarker(m)}};stage.onpointerleave=()=>{state.drag=null;stage.classList.remove('dragging')};stage.onwheel=e=>{e.preventDefault();const old=state.scale;const factor=e.deltaY<0?1.16:.86;const rect=stage.getBoundingClientRect();const mx=(e.clientX-rect.left-state.tx)/old,my=(e.clientY-rect.top-state.ty)/old;state.scale=Math.min(6,Math.max(.08,old*factor));state.tx=e.clientX-rect.left-mx*state.scale;state.ty=e.clientY-rect.top-my*state.scale;applyTransform()};
$('#zoomInBtn').onclick=()=>zoom(1.2);$('#zoomOutBtn').onclick=()=>zoom(.84);$('#fitBtn').onclick=fitMap;$('#locateBtn').onclick=()=>{state.tx=(stage.clientWidth-state.mapMeta.width*state.scale)/2;state.ty=(stage.clientHeight-state.mapMeta.height*state.scale)/2;applyTransform()};$('#clearPinsBtn').onclick=()=>{pins.clear();toast('Đã xóa toàn bộ ghim')};$('#exportPinsBtn').onclick=()=>download(JSON.stringify([...pins.values()],null,2),'aniimo-pins.json','application/json');$('#layersBtn').onclick=()=>$('#mapDrawer').classList.toggle('open');$('#closeDrawerBtn').onclick=()=>$('#mapDrawer').classList.remove('open');$('#layerSearch').oninput=renderLayers;$('#selectAllBtn').onclick=()=>{state.layerVisible.forEach((_,k)=>state.layerVisible.set(k,true));renderLayers();drawMarkers()};$('#clearAllBtn').onclick=()=>{state.layerVisible.forEach((_,k)=>state.layerVisible.set(k,false));renderLayers();drawMarkers()};$('#openLayersCta').onclick=()=>$('#mapDrawer').classList.add('open');}
function zoom(f){const s=$('#mapStage');const old=state.scale;state.scale=Math.min(6,Math.max(.08,old*f));state.tx=(s.clientWidth-state.mapMeta.width*state.scale)/2;state.ty=(s.clientHeight-state.mapMeta.height*state.scale)/2;applyTransform()}
function globalSearch(q){q=q.trim().toLowerCase();if(!q){toast('Nhập từ khóa để tìm');return}const direct=state.mapData.spawns.find(m=>[m.display_name,m.area_name,m.area_inferred_name,m.coordinate_key].some(v=>String(v||'').toLowerCase().includes(q)));if(direct){const x=(direct.normalized?.x||0)*state.mapMeta.width,y=(direct.normalized?.y||0)*state.mapMeta.height;state.tx=$('#mapStage').clientWidth/2-x*state.scale;state.ty=$('#mapStage').clientHeight/2-y*state.scale;applyTransform();showMarker(direct);return}switchView('aniimo');$('#aniimoSearch').value=q;renderAniimo()}
async function loadDataViews(){state.aniilog=await j('data/aniilog_data.json');state.catalog=await j('data/catalog-index-v2.json');state.checklist=await j('data/checklist_data.json');fillFilters();renderAniimo();renderItems();renderChecklist()}
function fillFilters(){const roles=[...new Set(state.aniilog.entries.map(e=>e.role).filter(Boolean))].sort();$('#roleFilter').innerHTML='<option value="">Tất cả vai trò</option>'+roles.map(v=>`<option>${esc(v)}</option>`).join('');const els=[...new Set(state.aniilog.entries.flatMap(e=>(e.elements||[]).map(x=>x.name)).filter(Boolean))].sort();$('#elementFilter').innerHTML='<option value="">Tất cả nguyên tố</option>'+els.map(v=>`<option>${esc(v)}</option>`).join('');const cats=state.catalog.categories.map(x=>x.label).sort();$('#itemCategoryFilter').innerHTML='<option value="">Tất cả danh mục</option>'+cats.map(v=>`<option>${esc(v)}</option>`).join('');const cc=state.checklist.categories.map(x=>x.label);$('#checkCategory').innerHTML='<option value="">Tất cả</option>'+cc.map(v=>`<option>${esc(v)}</option>`).join('');$('#aniimoSearch').oninput=renderAniimo;$('#roleFilter').onchange=renderAniimo;$('#elementFilter').onchange=renderAniimo;$('#itemSearch').oninput=renderItems;$('#itemCategoryFilter').onchange=renderItems;$('#checkSearch').oninput=renderChecklist;$('#checkCategory').onchange=renderChecklist}
function renderAniimo(){const q=$('#aniimoSearch').value.toLowerCase();const role=$('#roleFilter').value;const el=$('#elementFilter').value;const list=state.aniilog.entries.filter(e=>(!q||[e.name,e.aniilog_number,e.description].join(' ').toLowerCase().includes(q))&&(!role||e.role===role)&&(!el||(e.elements||[]).some(x=>x.name===el)));$('#aniimoCount').textContent=`${fmt(list.length)} hồ sơ`;$('#aniimoGrid').innerHTML=list.slice(0,240).map(e=>`<article class="aniimo-card" data-ani="${esc(e.id)}"><img src="${asset(e.icon)}" onerror="this.style.opacity=.25"><div><h3>${esc(e.aniilog_number)} · ${esc(e.name)}</h3><div class="sub">${esc(e.form_label||e.form_key||'')} · ${esc(e.role||'—')}</div><div class="chips">${(e.elements||[]).map(x=>`<span class="chip">${esc(translateElement(x.name))}</span>`).join('')}</div></div></article>`).join('');$$('#aniimoGrid .aniimo-card').forEach(c=>c.onclick=()=>showAniimo(c.dataset.ani))}
function showAniimo(id){const e=state.aniilog.entries.find(x=>x.id===id);if(!e)return;const html=`<div class="detail-head"><img class="detail-icon" src="${asset(e.icon)}"><div><h2>${esc(e.aniilog_number)} · ${esc(e.name)}</h2><div class="detail-sub">${esc(e.form_label||'')} · ${esc(e.role||'')}</div></div></div><div class="detail-block"><div class="detail-title">Mô tả</div><div class="muted">${esc(e.description||'Chưa có')}</div></div><div class="detail-block"><div class="detail-title">Chỉ số</div><div class="facts">${(e.stats||[]).map(s=>`<div class="fact"><label>${esc(translateStat(s.label))}</label><b>${esc(String(s.value))}</b></div>`).join('')}</div></div><div class="detail-block"><div class="detail-title">Vùng xuất hiện</div><div class="tag-row">${(e.locations||[]).flatMap(x=>x.areas||[]).slice(0,14).map(v=>`<span class="tag">${esc(v)}</span>`).join('')}</div></div>`;$('#detailPanel').style.display='block';$('#detailEmpty').hidden=true;$('#detailContent').hidden=false;$('#detailContent').innerHTML=html;switchView('map')}
function renderItems(){const q=$('#itemSearch').value.toLowerCase();const cat=$('#itemCategoryFilter').value;const list=state.catalog.entries.filter(e=>(!q||[e.name,e.description,e.type,e.catalog_category].join(' ').toLowerCase().includes(q))&&(!cat||e.catalog_category===cat));$('#itemCount').textContent=`${fmt(list.length)} mục · hiển thị tối đa 180 mục đầu tiên`;$('#itemGrid').innerHTML=list.slice(0,180).map(e=>`<article class="item-card"><img src="${asset(e.icon)}" onerror="this.style.opacity=.22"><div><h4>${esc(e.name)}</h4><div class="sub">${esc(e.catalog_category||e.type||'')} · ${esc(e.quality_display||e.quality||'')}</div><div class="sub">${fmt(e.overworld_spawn_count||0)} vị trí spawn</div></div></article>`).join('')}
function renderChecklist(){const q=$('#checkSearch').value.toLowerCase();const cat=$('#checkCategory').value;const list=state.checklist.entries.filter(e=>(!q||[e.name,e.category,e.form_label].join(' ').toLowerCase().includes(q))&&(!cat||e.category===cat));const done=list.filter(e=>state.checked.has(e.id)).length;$('#checklistSummary').textContent=`${fmt(done)} / ${fmt(state.checklist.entries.length)} đã hoàn thành`;$('#checklistList').innerHTML=list.map(e=>`<label class="check-row"><input type="checkbox" data-check="${esc(e.id)}" ${state.checked.has(e.id)?'checked':''}><div class="check-main"><b>${esc(e.name)}</b><div class="meta">${esc(e.aniilog_number||'')} · ${esc(e.form_label||'')}</div></div></label>`).join('');$$('#checklistList input').forEach(i=>i.onchange=()=>{i.checked?state.checked.add(i.dataset.check):state.checked.delete(i.dataset.check);localStorage.setItem('aniimo-atlas-checks',JSON.stringify([...state.checked]));renderChecklist()})}
function switchView(v){state.view=v;$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('.view').forEach(x=>x.hidden=!x.id.endsWith(v));if(v!=='map')$('#mapDrawer').classList.remove('open')}
function bindGlobal(){ $$('#sidebar .nav-btn').forEach(b=>b.onclick=()=>{switchView(b.dataset.view);$('#sidebar').classList.remove('open')});$('#globalSearch').onkeydown=e=>{if(e.key==='Enter')globalSearch(e.target.value)};window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#globalSearch').focus()}if(e.key==='Escape')$('#mapDrawer').classList.remove('open')});$('#sidebarToggle').onclick=()=>$('#sidebar').classList.toggle('open');$('#fullscreenBtn').onclick=()=>document.documentElement.requestFullscreen?.();$('#shareBtn').onclick=()=>{const u=new URL(location.href);u.searchParams.set('map',state.mapId);navigator.clipboard?.writeText(u.href);toast('Đã sao chép liên kết bản đồ')};$('#resetBtn').onclick=()=>{state.search='';$('#globalSearch').value='';fitMap();toast('Đã về mặc định')};bindMap();}
function asset(p){if(!p)return'';if(/^https?:\/\//.test(p))return p;return p.split('?')[0]}
function translateElement(v){return ({Fire:'Lửa',Water:'Nước',Grass:'Cỏ',Ice:'Băng',Electric:'Điện',Wind:'Gió',Rock:'Đá',Metal:'Kim loại',Holy:'Thánh',Dark:'Bóng tối',Poison:'Độc',Psychic:'Tâm linh',Normal:'Thường'})[v]||v}
function translateStat(v){return ({'Magic Attack':'Công phép','Magic Defense':'Thủ phép','Defense':'Phòng thủ','Attack':'Công','Break':'Phá giáp','EP Regen':'Hồi EP','HP':'HP'})[v]||v}
function title(s){return s.replace(/[-_]/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function fmt(n){return new Intl.NumberFormat('vi-VN').format(n||0)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function download(text,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
init().catch(err=>{console.error(err);toast('Không thể tải dữ liệu. Hãy chạy qua HTTP server/GitHub Pages.')});
